In [1]:
from sklearn.datasets import load_boston

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import numpy as np

In [5]:
data = load_boston()

In [6]:
data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
        19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
        20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
        23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
        33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
        21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
        20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
        23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
        15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
        17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
        25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
        23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
        32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
        34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
        20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
        26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
        31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
        22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
        42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
        36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
        32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
        20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
        20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
        22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
        21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
        19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
        32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
        18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
        16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
        13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
         7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
        12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
        27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
         8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
         9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
        10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
        15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
        19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
        29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
        20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
        23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9]),
 'feature_names': array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
        'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7'),
 'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n        - PTRATIO  pupil-teacher ratio by town\n        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\n        - LSTAT    % lower status of the population\n        - MEDV     Median value of owner-occupied homes in $1000's\n\n    :Missing Attribute Values: None\n\n    :Creator: Harrison, D. and Rubinfeld, D.L.\n\nThis is a copy of UCI ML housing dataset.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/housing/\n\n\nThis dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.\n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\n\nThe Boston house-price data has been used in many machine learning papers that address regression\nproblems.   \n     \n.. topic:: References\n\n   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.\n   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.\n",
 'filename': 'C:\\Users\\ruesm\\Miniconda3\\envs\\tbe\\lib\\site-packages\\sklearn\\datasets\\data\\boston_house_prices.csv'}

In [7]:
df = pd.DataFrame(data["data"], columns = data["feature_names"])

In [8]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [9]:
df["y"] = data['target']

In [10]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,y
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [11]:
import statsmodels.formula.api as smf

In [12]:
import statsmodels.api as sm

In [29]:
results = smf.ols('y ~ LSTAT + CRIM + ZN + np.exp(INDUS) + CHAS + NOX + RM + AGE + DIS + RAD + TAX + PTRATIO + B', data=df).fit()

In [30]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.735
Method:                 Least Squares   F-statistic:                     108.5
Date:                Sun, 28 Feb 2021   Prob (F-statistic):          3.28e-135
Time:                        19:52:50   Log-Likelihood:                -1498.1
No. Observations:                 506   AIC:                             3024.
Df Residuals:                     492   BIC:                             3083.
Df Model:                          13
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        36.9536      5.110      7.232      0.000      26.914      46.993
LSTAT            -0.5288      0.051    -10.436      0.000      -0.628      -0.429
CRIM             -0.1069      0.033     -3.256      0.001      -0.171      -0.042
ZN                0.0461      0.014      3.385      0.001       0.019       0.073
np.exp(INDUS)  2.898e-12   2.32e-12      1.250      0.212   -1.66e-12    7.45e-12
CHAS              2.6961      0.856      3.150      0.002       1.014       4.378
NOX             -16.8161      3.711     -4.531      0.000     -24.108      -9.524
RM                3.7681      0.416      9.054      0.000       2.950       4.586
AGE               0.0007      0.013      0.050      0.960      -0.025       0.027
DIS              -1.4689      0.195     -7.518      0.000      -1.853      -1.085
RAD               0.3477      0.074      4.683      0.000       0.202       0.494
TAX              -0.0144      0.004     -3.624      0.000      -0.022      -0.007
PTRATIO          -0.9547      0.130     -7.363      0.000      -1.210      -0.700
B                 0.0092      0.003      3.413      0.001       0.004       0.014
==============================================================================
Omnibus:                      179.810   Durbin-Watson:                   1.076
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              798.521
Skew:                           1.534   Prob(JB):                    4.01e-174
Kurtosis:                       8.335   Cond. No.                     3.00e+12
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large,  3e+12. This might indicate that there are
strong multicollinearity or other numerical problems.

In [31]:
print(results.predict())

[30.0225974  25.02931192 30.5614314  28.79202574 28.11196736 25.45542997
 23.03345735 19.53509216 11.50392789 18.94098032 18.98822539 21.61888972
 20.93095456 19.56533995 19.28190332 19.31285191 20.54911189 16.89415028
 16.20898587 18.41027037 12.49684187 17.6555308  15.78950832 13.77255141
 15.65652045 13.39261605 15.45752233 14.69210091 19.51731512 20.84249196
 11.42116856 18.04625184  8.7655032  14.26384167 13.68085168 23.92308746
 22.4506117  23.22927039 23.02544925 31.42366838 34.27294094 28.080108
 25.28479946 24.68062071 23.00931412 22.17295135 20.47910982 18.0662431
  9.11400923 17.26701428 21.37889232 24.07921855 27.76411941 24.16589888
 14.93274561 31.35690509 24.81003506 33.27864406 21.99857824 21.30011833
 18.08120997 18.70415809 24.19191588 22.74059091 23.53812483 30.27828519
 25.44529654 20.98414223 17.28333163 20.65208045 25.04179917 21.58995664
 24.41619433 23.88828616 25.17368792 23.62852649 22.59253868 23.0159129
 20.91458666 22.10459275 28.41458132 26.99931493 26.05655925 25.08246078
 24.85142219 27.85802676 22.23572827 25.96874185 30.69440434 30.84791681
 27.14919887 27.4453473  28.78871573 28.94673011 26.88402114 28.6193341
 24.71670082 35.71918437 35.06692719 32.20824411 24.39830741 25.4177253
 19.66709572 20.13751129 21.26207856 18.36101536 17.00099474 20.57119375
 22.46238577 19.5847549  20.47641414 26.2847645  20.53862798 20.47083489
 24.94730173 20.20564864 23.15207149 23.47843055 20.11663954 20.57958074
 22.13872513 22.68921307 20.76135464 16.54474059 20.76898879 22.69592469
 14.79861393 14.6839387  18.41972552 13.55984753 19.5288862  18.91238812
 19.56831518 15.27183384 12.78322635 16.74406782 15.37788543 18.84570863
 13.29547824 15.92838662 13.02769359  3.45048225 14.48082217 12.02571036
  8.61518581 11.912703   15.76499092  8.40119591  9.60463113 14.70268258
 20.74073    18.24095838 20.09308575 17.21651092 22.28184957 20.05846569
 13.59704217 32.91622802 28.7164927  25.4827269  32.40285109 36.4192763
 40.19604106 41.45679008 24.46192357 25.07339761 36.82342393 22.78396942
 26.0719077  26.31473811 22.23105458 23.96845512 23.09371845 29.17744591
 26.64951733 30.84287343 25.74201565 29.26310189 31.53404146 33.16180415
 34.91963224 28.02035459 34.11943923 31.24563227 22.97980545 25.01174039
 36.09458744 33.25608778 32.2687633  34.33962146 30.61295282 30.14950878
 32.76845611 32.04744171 31.50669517 40.95240177 35.99333459 32.53054253
 34.56112868 29.85068939 30.39694454 29.13537147 36.8771951  42.14118152
 43.29534284 22.66022489 23.63629272 17.8019763  23.45407271 16.95556545
 22.34068176 17.0031537  22.69872219 25.17654768 11.03878482 24.47381889
 26.60407115 28.33169505 24.89209119 29.67962802 33.3296752  23.90578232
 32.29171865 29.90690379 38.47352614 39.89650444 37.70370041 32.54334654
 35.59069764 31.41578834 24.65878241 33.42885834 38.16391602 37.27650199
 31.88652438 25.4430442  30.26933505 32.86880817 28.49825506 28.48969703
 27.32499504 23.80233985 24.18210454 27.4883976  16.38334938 13.42651301
 20.06265035 19.89971869 21.3197537  24.10955303 24.24516175 25.0956676
 24.96028388 29.93038944 23.81534544 21.53771715 37.52187194 43.52376433
 36.75268988 35.28251884 35.07972188 37.43077179 41.22367949 34.7015952
 36.1067621  28.57863658 31.48278087 41.00564389 39.53853268 25.78980514
 22.38524805 27.29513661 28.58175678 35.51668895 36.16431603 33.84444441
 35.64271248 34.89841741 30.39759526 35.54176323 38.99602742 34.5657327
 40.56340715 44.74473725 31.46399905 27.23126612 20.10269405 27.10406698
 27.26887794 26.95566878 33.48799166 34.44297872 31.88998854 25.66006012
 24.26878574 28.2889269  27.19467873 19.37027295 29.06757632 31.83666605
 30.69513095 28.95086825 28.90006775 32.81113698 33.52593892 31.09811441
 35.86566911 33.03258825 28.61212578 23.56365688 18.55475695 26.86096837
 23.24372949 25.51715866 25.43623003 20.52348724 17.56473298 18.33961232
 24.24938334 21.28890792 24.94101756 24.92695056 22.9392743  19.51848915
 25.17869238 24.73810572 23.75077064 19.39289722 20.96920504 24.04019964
 21.38601793 19.83129581 23.19597974 22.41510528 21.82551455 20.89122807
 20.42777711 19.54997627 22.42845445 21.50911479 21.69096544 30.28204639
 21.80084358 27.63944463 28.49116442 16.42445411 14.66239015 25.16694372
 27.63056115 22.00432721 20.33239858 20.37309801 16.7245609  25.72685418
 14.32149287 16.59140391 19.71070737 22.79646336 22.3016796  19.28968915
 22.76097069 19.00819588 18.35181349 20.33157118 37.45782518 14.44570229
 15.6259573  10.91903765 23.83348866 32.61386604 34.56316124 24.9038074
 26.02358764  6.07139397  0.75014564 25.25196144 17.67404362 20.15659752
 15.78057404 16.79048533 14.39399329 18.41972204 13.42280126 13.05197525
  3.3237545   8.04457401  6.15807037  5.61728978  6.45566642 14.21989843
 17.22663545 17.2951166   9.90281919 20.21757891 17.95139597 20.28145109
 19.26193082 16.33020259  6.54783498 10.84975769 11.85635049 17.78555067
 18.23095603 13.01014693  7.39966262  8.26395414  8.09658253 19.99411898
 13.60010643 19.74981366 15.27465973 16.88276193  1.67846492 11.7847414
 -4.21404177  9.56909498 13.3434638   6.93036866  6.25221062 14.62839977
 19.62688769 18.16072091 18.49181374 13.12912183 14.60150161  9.95171087
 16.31641648 14.15393155 14.26185141 13.03594629 18.08674539 18.59620911
 21.47082464 17.07906265 16.03094383 13.40132992 14.60485126  8.88545774
  4.90018006 13.10019266 12.75122499 17.31461316 18.77259752 18.07695132
 11.56471175 12.02713926 17.71904662 18.16573173 17.52570385 17.23227256
 16.56918259 19.40497896 18.5862775  22.45528683 15.32547641 15.86467891
 12.75758176 12.96346794 17.21867261 18.53876674 19.06095654 20.18242226
 19.79337986 22.45532778 20.29441003 17.88228655 14.3977719  16.83383126
 16.89262061 18.5121943  20.05632567 22.83212271 22.34055214 25.48557904
 16.31459922 15.98396891 20.42881374 11.47814679 19.12181961 21.80074275
 23.3366792  26.95724925 28.41842597 20.97574428 19.37938323 22.13940491
 19.56120627 21.25172283 13.88926423 10.24234295  5.67716382 15.77120203
 17.96357008 20.54378736 20.51457625 16.78557812 13.90876538 19.01653787
 21.19835756 18.36500853 20.3630436  23.39897078 22.26120384 27.48986961
 25.99673198 22.23966113]

In [35]:
df["AGE"]>=60

0       True
1       True
2       True
3      False
4      False
       ...
501     True
502     True
503     True
504     True
505     True
Name: AGE, Length: 506, dtype: bool

In [40]:
df[(df["AGE"]>=70) & (df["ZN"] == 0)]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,y
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
14,0.63796,0.0,8.14,0.0,0.538,6.096,84.5,4.4619,4.0,307.0,21.0,380.02,10.26,18.2
17,0.78420,0.0,8.14,0.0,0.538,5.990,81.7,4.2579,4.0,307.0,21.0,386.75,14.67,17.5
20,1.25179,0.0,8.14,0.0,0.538,5.570,98.1,3.7979,4.0,307.0,21.0,376.57,21.02,13.6
21,0.85204,0.0,8.14,0.0,0.538,5.965,89.2,4.0123,4.0,307.0,21.0,392.53,13.83,19.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6.0,391.0,19.2,396.90,14.33,16.8
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9